# Generated by Django 4.2.11 on 2026-04-24 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Vide = tous les utilisateurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
